### ISSUE TITLE
Design principles for web developers

### ISSUE THREAD

**Issue by cynthia** [w3ctag/design-principles#302] opened 2021-04-14 15:43 UTC
There is a bunch of good information for non-spec authors in here that we should try to spin out as a different document. Bikeshed apparently has tooling to do this.

**Comment by LeaVerou** [comment] 2021-04-14 15:50
Closed as duplicate of https://github.com/w3ctag/design-principles/issues/268

**Closed by LeaVerou** 2021-04-14 15:50 UTC
