### ISSUE TITLE
Guide spec authors to use one manifest (web app manifest)

### ISSUE THREAD

**Issue by travisleithead** [w3ctag/design-principles#95] opened 2018-04-07 04:46 UTC
We should provide guidelines on what to do if you want to create some data that should be in a manifest. We would like to avoid a proliferation of manifest files.

E.g., Assume you should integrate into web-app-manifest. If you can't for [good reason here] then [do this alternat thing].

See also https://github.com/w3ctag/design-reviews/issues/231#issuecomment-379432055 which motivated the opening of this issue (among other previous discussions).

**Comment by hober** [comment] 2019-03-21 20:13
See also https://github.com/w3ctag/design-reviews/issues/344

**Comment by BigBlueHat** [comment] 2019-09-26 15:23
The Web App Manifest doesn't actually (on it's own) "manifest" anything. It points to icons and metadata to be used in launcher icon creation and application discovery. It then points to a ServiceWorker for actually "manifestation" of the Web App and to a "scope" for limiting navigation within the constrained navigation environment (i.e. "standalone" browser environment).

Other manifest formats (like Audiobooks and Publication Manifest) encode a (deliberately) static, non-procedural list of resources--as one would do in a physical manifest document (i.e. the list of things to include + metadata about that list).

The Publication WG did look into Web App Manifest as a foundation, but it's dependency on ServiceWorkers (and therefore JavaScript) to do the actually manifestation brought in a new significant requirement that actually made a publication (or audiobook's) construction less dependable and more fragile and subjective (vs. a consistently structured, static list of resources).

Hopefully that clears up some of the confusion caused by the varied use of the word "manifest" among current W3C specifications.

**Comment by dbaron** [comment] 2020-03-30 16:10
One other question about web app manifests that might be relevant here:  is it OK for web app manifest to be the only way to get to a feature, or should everything in web app manifest be an alternative way of getting to a feature that's available some other way (but that might, say, make it available before the user has interacted with the app)?  (I think I've seen that distinction discussed elsewhere at some point recently.)

**Comment by torgo** [comment] 2020-03-30 16:12
Will add to breakout C this week.

**Comment by kenchris** [comment] 2020-03-31 08:10
- point to 2.2 for naming (underscore)
- if the fetching of the metadata/manifest is at a different time at than existing manifest, a new manifest can be considered (example payment handler manifest) but if at all avoidable, please extend an existing manifest
- if a new key is added, make sure it is really needed (define well thought out use-cases) and check if a similar key exists. If an existing key does more or less what is needed, work with the existing spec to extend it to your use-case if possible.

**Comment by torgo** [comment] 2020-03-31 08:11
@tantek's text from issue #148 
> Here at #w3cTPAC 2019 I’m learning that there are quite a few different manifest file format efforts by different groups for different specifications with different but often similar use-cases. Filing this design issue per @hober’s request to track the growing number of manifest formats and approaches to hopefully collapsing and reducing them.
> 
> Here is a few I know of along with their individual TAG review issues.
> 
>     Web App Manifest (W3CTAG w3ctag/design-reviews#30)
>     Payment Method Manifest (W3CTAG w3ctag/design-reviews#162, Payment Method w3ctag/design-reviews#27, W3CTAG w3ctag/design-reviews#231 Payment Handler)
>     Audio Book Manifest (W3CTAG w3ctag/design-reviews#345)
>     Publication Manifest (W3CTAG w3ctag/design-reviews#344)
> 
> And one apparent need for a manifest: W3CTAG w3ctag/design-reviews#218. There are likely others, please add more below.
> 
> From a web author, developer, publisher perspective, it would be great if we could simplify the number of manifests, ideally one, perhaps with core properties, optional properties for specific use-cases, and a method of expanding each of those by separate working groups for maximum re-use and avoiding collisions / duplication of slightly different properties.
> 
> This issue is intended as a meta-issue just to track the growing number of manifests.
> 
> For specific proposals to provide guidelines to both spec and web authors about how to create some data and provide it in a manifest file, see: W3CTAG w3ctag/design-reviews#95 (please do not mark as duplicate, I think these serve two different purposes). Thanks for your consideration!

**Comment by ylafon** [comment] 2020-03-31 08:12
We need to define the different kinds of manifest that are currently known by their function. App manifest should always be a Web App Manifest (or extension of it), parameters for a specific function (like Payment Manifest) are a completely different type. Publication Manifest, using json-ld is another type as well.

Note that in all case, as discussed in today's breakout, the naming conventions should be harmonised.

**Comment by torgo** [comment] 2020-03-31 08:12
Suggested title "Be careful about introducing new types of manifest files"

**Comment by torgo** [comment] 2020-07-06 16:15
We agreed that the addition of PR #189 allows us to close this.

**Closed by torgo** 2020-07-06 16:15 UTC
