### ISSUE TITLE
Give guidance on algorithms

### ISSUE THREAD

**Issue by annevk** [w3ctag/design-principles#72] opened 2017-08-09 11:46 UTC
See https://github.com/w3c/requestidlecallback/issues/61 for an example.

I'm not entirely sure how to phrase this, but we basically want algorithms in specifications to reflect best practices in programming. So no stack introspection, side-effect-free if possible, etc.

**Comment by annevk** [comment] 2017-08-09 11:46
Relates a bit to #10 I suppose.

**Comment by torgo** [comment] 2018-04-06 02:40
Closed as a duplicate of #10.

**Closed by torgo** 2018-04-06 02:40 UTC
